### ISSUE TITLE
Unexpected error during

### ISSUE THREAD

**Issue by don86nl** [haade-administrator/korvo-esphome#5]
Hi Haade,

Thanks for your work. I'm not getting the microphone to work. When using a wake-word, the it seems to be detected, because only using the right wakeword produces the following error:

> [10:28:26][E][voice_assistant:693]: Error: wake-stream-failed - Unexpected error during wake-word-detection

Any idea? 

Part from log:

> [10:28:24][D][voice_assistant:126]: microphone not running
> [10:28:24][D][voice_assistant:210]: Requesting start...
> [10:28:24][D][voice_assistant:439]: State changed from START_PIPELINE to STARTING_PIPELINE
> [10:28:24][D][voice_assistant:126]: microphone not running
> [10:28:24][D][voice_assistant:476]: Client started, streaming microphone
> [10:28:24][D][voice_assistant:439]: State changed from STARTING_PIPELINE to START_MICROPHONE
> [10:28:24][D][voice_assistant:445]: Desired state set to STREAMING_MICROPHONE
> [10:28:24][D][voice_assistant:163]: Starting Microphone
> [10:28:24][D][voice_assistant:439]: State changed from START_MICROPHONE to STARTING_MICROPHONE
> [10:28:24][D][voice_assistant:563]: Event Type: 1
> [10:28:24][D][voice_assistant:566]: Assist Pipeline running
> [10:28:24][D][voice_assistant:439]: State changed from STARTING_MICROPHONE to STREAMING_MICROPHONE
> [10:28:24][D][voice_assistant:563]: Event Type: 9
> [10:28:26][D][voice_assistant:563]: Event Type: 0
> [10:28:26][E][voice_assistant:693]: Error: wake-stream-failed - Unexpected error during wake-word-detection
> [10:28:26][D][voice_assistant:556]: Signaling stop...
> [10:28:26][D][voice_assistant:439]: State changed from STREAMING_MICROPHONE to STOP_MICROPHONE
> [10:28:26][D][voice_assistant:445]: Desired state set to IDLE
> [10:28:26][D][voice_assistant:439]: State changed from STOP_MICROPHONE to STOPPING_MICROPHONE
> [10:28:26][D][light:036]: '${device_name} Light' Setting:
> [10:28:26][D][light:051]:   Brightness: 100%
> [10:28:26][D][light:059]:   Red: 100%, Green: 0%, Blue: 0%
> [10:28:26][D][voice_assistant:563]: Event Type: 2
> [10:28:26][D][voice_assistant:653]: Assist Pipeline ended
> [10:28:26][D][voice_assistant:439]: State changed from STOPPING_MICROPHONE to IDLE
> [10:28:26][D][voice_assistant:439]: State changed from IDLE to START_PIPELINE
> [10:28:26][D][voice_assistant:445]: Desired state set to START_MICROPHONE
> [10:28:26][D][voice_assistant:126]: microphone not running
> [10:28:26][D][voice_assistant:210]: Requesting start...
> [10:28:27][D][voice_assistant:439]: State changed from START_PIPELINE to STARTING_PIPELINE
> [10:28:27][D][voice_assistant:126]: microphone not running

**Comment by don86nl** [comment]
Log in Home Assistant:
```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/pipeline.py", line 713, in wake_word_detection
    result = await self.wake_word_entity.async_process_audio_stream(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/wake_word/__init__.py", line 113, in async_process_audio_stream
    result = await self._async_process_audio_stream(stream, wake_word_id)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/wyoming/wake_word.py", line 141, in _async_process_audio_stream
    return wake_word.DetectionResult(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: DetectionResult.__init__() missing 1 required positional argument: 'wake_word_phrase'
```

**Comment by haade-administrator** [comment]
hi install 
assist microphone
openwakeword
whisper

[![Open your Home Assistant instance and show the add-on store.](https://my.home-assistant.io/badges/supervisor_store.svg)](https://my.home-assistant.io/redirect/supervisor_store/)

**Comment by don86nl** [comment]
Thanks, haade for helping out.
However, I do have everything installed, besides local microphone. Isnt that just for using a mic on the hardware HA is installed?

My assistant setup:
Home Assistant cloud (stt & tts. I did try whisper, no change in the error.)
Openwakeword; hey_jarvis
Dutch language

**Comment by haade-administrator** [comment]
ok i look next time the code for debugging
